#!/usr/bin/env python3
"""
AiMetaverse Agent Swarm - Dataset + Runner Bootstrap
- Creates datasets for each assistant role
- Creates a local task bus (simulated SQS) so you can run end-to-end offline
- Produces a single runner that routes tasks to agents and writes outputs to ./out/

Run:
  python aimetaverse_bootstrap.py
Then:
  python run_swarm_local.py --demo
"""

import json
import os
import time
import argparse
from pathlib import Path
from datetime import datetime

ROOT = Path.cwd()
DATA = ROOT / "datasets"
OUT = ROOT / "out"
BUS = ROOT / "bus"  # simulated SQS: task files placed here

def now_iso():
    return datetime.utcnow().isoformat() + "Z"

def write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

def write_json(path: Path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2), encoding="utf-8")

def seed_datasets():
    """Create starter datasets that are actually usable."""
    # Earth: code structures / templates
    earth = {
        "version": "0.1",
        "created_at": now_iso(),
        "templates": [
            {
                "name": "python_service_module",
                "language": "python",
                "files": [
                    "src/{service_name}/__init__.py",
                    "src/{service_name}/main.py",
                    "tests/test_{service_name}.py",
                    "README.md",
                    "pyproject.toml"
                ],
                "snippets": {
                    "main.py": "def handler(event, context=None):\n    return {'ok': True, 'event': event}\n",
                    "README.md": "# {service_name}\n\nGenerated by Earth.\n"
                }
            },
            {
                "name": "web_frontend_stub",
                "language": "html",
                "files": [
                    "web/index.html",
                    "web/app.js",
                    "web/styles.css"
                ],
                "snippets": {
                    "index.html": "<!doctype html><html><head><meta charset='utf-8'><title>{app}</title></head><body><div id='app'></div><script src='app.js'></script></body></html>\n"
                }
            }
        ]
    }
    write_json(DATA / "earth" / "code_structures.json", earth)

    # Moon: syntax error -> fix pairs
    moon = {
        "version": "0.1",
        "created_at": now_iso(),
        "samples": [
            {
                "language": "python",
                "broken": "def add(a,b)\n    return a+b\n",
                "fixed":  "def add(a, b):\n    return a + b\n",
                "issue":  "missing colon after function signature"
            },
            {
                "language": "javascript",
                "broken": "function hi(){ console.log('hi') \n",
                "fixed":  "function hi(){ console.log('hi') }\n",
                "issue":  "missing closing brace"
            }
        ]
    }
    write_json(DATA / "moon" / "syntax_fixes.json", moon)

    # Sun: benchmark hints + optimization playbook
    sun = {
        "version": "0.1",
        "created_at": now_iso(),
        "patterns": [
            {"name": "avoid_n_plus_one", "desc": "Batch requests; prefer single query + join."},
            {"name": "cache_hot_paths", "desc": "Memoize repeated computations; add TTL cache."},
            {"name": "lazy_loading", "desc": "Load data only when needed; use generators for large datasets."},
            {"name": "async_io", "desc": "Use async/await for I/O operations to prevent blocking."},
            {"name": "index_databases", "desc": "Add database indexes on frequently queried columns."},
            {"name": "compress_assets", "desc": "Minify and compress CSS/JS/images for faster loading."},
            {"name": "connection_pooling", "desc": "Reuse database connections instead of creating new ones."},
            {"name": "algorithm_optimization", "desc": "Choose O(n log n) over O(n²) algorithms for large datasets."}
        ]
    }
    write_json(DATA / "sun" / "optimization_patterns.json", sun)

def main():
    parser = argparse.ArgumentParser(description="Bootstrap AiMetaverse Agent Swarm datasets")
    parser.add_argument("--force", action="store_true", help="Overwrite existing datasets")
    args = parser.parse_args()

    if DATA.exists() and not args.force:
        print(f"Datasets already exist at {DATA}. Use --force to overwrite.")
        return

    print("Seeding datasets...")
    seed_datasets()
    print(f"Datasets created in {DATA}")

    # Create output and bus directories
    OUT.mkdir(exist_ok=True)
    BUS.mkdir(exist_ok=True)
    print(f"Created directories: {OUT}, {BUS}")

if __name__ == "__main__":
    main()